version: '3'
services:
    dockerkit:
        build: .
        volumes: 
            - ./config.json:/usr/app/config.json
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: host
