name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  tsc:
    name: Compiling
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: yarn install
      - name: Run TypeScript Compiler
        run: tsc
