name: Docker Build

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building and Pushing Image to DockerHub
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u dunklesToast --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag dunklestoast/dockerkit:${{steps.vars.outputs.tag}} --tag dunklestoast/dockerkit:latest
      - name: Push the tagged Docker image
        run: docker push dunklestoast/dockerkit:${{steps.vars.outputs.tag}}
      - name: Push the latest Docker image
        run: docker push dunklestoast/dockerkit:latest