name: Docker Build

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building and Pushing Image to DockerHub
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dunklesToast
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Login to GitHub CR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.H5_GITHUB_TOKEN }}
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(git describe --abbrev=0)
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            dunklestoast/DockerKit:latest
            dunklestoast/DockerKit:${{steps.vars.outputs.tag}}
            ghcr.io/dunklestoast/DockerKit:latest
            ghcr.io/dunklestoast/DockerKit:${{steps.vars.outputs.tag}}